export const SHIFT_STATUS_COLORS = {
  ASSIGNED: "#3B82F6",
  ADDITIONAL: "#22C55E",
  SWAP: "#A855F7",
  HOLIDAY: "#EF4444",
  REQUESTED_HOLIDAY: "#EAB308",
  AVAILABLE: "#9CA3AF",
  CANCELLED: "#6B7280",
} as const;

export const ROLES = {
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
  MANAGER: "MANAGER",
  EMPLOYEE: "EMPLOYEE",
} as const;
